version: '3'


services:

  postgres-db-results-zno:
    image: postgres:latest
    restart: always
    container_name: postgres-db-results-zno
    environment:
      POSTGRES_DB: results_zno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - zno
      
  postgres-db-results-zno-new:
    image: postgres:latest
    container_name: postgres-db-results-zno-new
    environment:
      POSTGRES_DB: results_zno_new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - zno

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    networks:
      - zno

  funnel:
    build: 
      context: ./funnel
      dockerfile: Dockerfile-funnel
    environment:
      - HOST_DB=localhost
    depends_on:
      - postgres-db-results-zno
    networks:
      - zno
    volumes:
     - ./my_app/funnel/funnel.py:/funnel/funnel.py
    #  - ./app_data_loading/execution_time.txt:/app_data_loading/execution_time.txt
    
     
networks:
  zno: