# Використовуємо базовий образ Python
FROM python:latest

# Встановлюємо залежності
RUN pip install psycopg2-binary pandas

# Копіюємо файли проекту в контейнер
ADD funnel.py /app/
ADD data/Odata2021File.csv /app/data/

# Встановлюємо робочу директорію
WORKDIR /app